"""Report grounding: never emit numbers that are absent from evidence."""


from __future__ import annotations

import re
from typing import Any, Callable

_NUMBER = re.compile(r"-?\d+(?:\.\d+)?")


def numbers_in(value: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(value, dict):
        for item in value.values():
            found |= numbers_in(item)
    elif isinstance(value, (list, tuple)):
        for item in value:
            found |= numbers_in(item)
    else:
        found.update(_NUMBER.findall(str(value)))
    return found


def detect_chartable_data(analyst_results: list[dict[str, Any]]) -> dict[str, Any] | None:
    """Detect if evidence contains multi-row numeric tabular data suitable for visualization."""
    for item in analyst_results or []:
        if not item.get("success"):
            continue
        rows = item.get("result") or []
        if len(rows) > 1 and isinstance(rows[0], dict):
            keys = list(rows[0].keys())
            if len(keys) >= 2:
                # Find category key (str) and numeric key (int/float)
                str_key = None
                num_key = None
                for key in keys:
                    val = rows[0][key]
                    if isinstance(val, (int, float)) and num_key is None:
                        num_key = key
                    elif isinstance(val, str) and str_key is None:
                        str_key = key
                if num_key and str_key:
                    return {
                        "chartable": True,
                        "title": f"Visualization for {item.get('subquestion', 'query')}",
                        "x_col": str_key,
                        "y_col": num_key,
                        "data": rows,
                    }
                elif num_key and len(keys) >= 2:
                    return {
                        "chartable": True,
                        "title": f"Visualization for {item.get('subquestion', 'query')}",
                        "x_col": keys[0],
                        "y_col": num_key,
                        "data": rows,
                    }
    return None


def grounded_report(
    question: str,
    analyst_results: list[dict[str, Any]],
    llm_caller: Callable[[str], str] | None = None,
) -> str:
    # Extract direct key findings from evidence
    direct_findings: list[str] = []
    evidence_items: list[str] = []

    for idx, item in enumerate(analyst_results or [], start=1):
        sql = item.get("sql", "")
        if not item.get("success"):
            evidence_items.append(f"{idx}. ❌ **FAILED**: `{sql}`\n   - Error: {item.get('error')}")
            continue
        rows = item.get("result") or []
        evidence_items.append(f"{idx}. 💻 `{sql}`\n   - **Result**: `{rows}`")

        # Format rows into readable findings
        if rows:
            if len(rows) == 1 and isinstance(rows[0], dict):
                row_str = ", ".join(f"**{k}**: {v}" for k, v in rows[0].items())
                direct_findings.append(f"- {row_str}")
            elif len(rows) > 1 and isinstance(rows[0], dict):
                first_key = list(rows[0].keys())[0]
                vals = [str(r.get(first_key)) for r in rows if r.get(first_key) is not None]
                if vals:
                    direct_findings.append(f"- **{first_key.title()}s** ({len(vals)} items): " + ", ".join(vals[:10]) + ("..." if len(vals) > 10 else ""))
            else:
                direct_findings.append(f"- {rows}")
        else:
            direct_findings.append("- *No rows returned*")

    chart_spec = detect_chartable_data(analyst_results)
    chart_text = f"\n\n[Chart Suggested: {chart_spec['title']} ({chart_spec['x_col']} vs {chart_spec['y_col']})]" if chart_spec else ""

    evidence_block = "\n".join(evidence_items)

    if llm_caller is not None:
        try:
            prompt = (
                "You are an executive data analyst synthesis engine.\n"
                "Synthesize a clear, direct, professional answer to the user's business question based strictly on the retrieved SQL evidence below.\n\n"
                f"Question: {question}\n\n"
                f"Retrieved Evidence:\n{evidence_block}\n\n"
                "Instructions:\n"
                "1. Start DIRECTLY with the answer (Executive Summary).\n"
                "2. State the key facts, counts, totals, or names clearly upfront.\n"
                "3. If multiple items exist, format them with clean bullet points.\n"
                "4. Do NOT output any SQL code, HTML tags, <details>, or <summary> blocks under any circumstances. Output ONLY the executive plain text/markdown answer."
            )
            llm_synthesis = llm_caller(prompt).strip()
            # Programmatically remove any <details>...</details> or raw HTML evidence blocks if generated by LLM
            llm_synthesis = re.sub(r"<details>.*?</details>", "", llm_synthesis, flags=re.DOTALL)
            llm_synthesis = re.sub(r"</?details>", "", llm_synthesis)
            llm_synthesis = re.sub(r"</?summary>", "", llm_synthesis)
            llm_synthesis = llm_synthesis.strip()

            if llm_synthesis:
                return f"### 💡 Answer\n\n{llm_synthesis}{chart_text}"
        except Exception:
            pass

    # Fallback format if LLM synthesis is not available
    findings_text = "\n".join(direct_findings) if direct_findings else "No evidence retrieved."
    return f"### 💡 Answer Summary\n\n{findings_text}{chart_text}"


def assert_report_grounded(report: str, analyst_results: list[dict[str, Any]]) -> bool:
    allowed = numbers_in(analyst_results)
    for number in numbers_in(report):
        if number not in allowed:
            return False
    return True
